help("head")
library(datasets)
data("iris")
summary(iris)
head(iris)
names(iris) <- tolower(names(iris))
library(dplyr)
library("dplyr")
names(iris) <- tolower(names(iris))
library(dplyr)
install.packages("dplyr")
names(iris) <- tolower(names(iris))
library(dplyr)
virginica<-filter(iris,Species == "virginica")
virginica<-filter(iris,species == "virginica")
head(virginica)
setosa<-filter(iris,species=="setosa")
head(setosa)
versicolor<-filter(iris,species=="versicolor")
head(versicolor)
hist(virginica$sepal.length)
virgin<-transform(iris,species=factor(species))
boxplot(sepal.length~species,virgin,xlab = species,ylab = sepal.length)
boxplot(sepal.width~species, data=virginica)
boxplot(sepal.width~species, data=virginica)
boxplot(sepal.width~species, data=virginica, xlab = virginica, ylab = sepal.width)
boxplot(sepal.width~species, data=virginica, xlab = virginica, ylab = sepal.width)
boxplot(sepal.width~species, data=virginica, xlab = "virginica", ylab = "sepal.width")
attach(versicolor)
plot(petal.length)
attach(virginica)
plot(sepal.length)
attach(virginica)
plot(sepal.length,xlab = "virginica",ylab = "sepal.length")
hist(virgin$sepal.length,xlab = "virginica",ylab = sepal.length)
hist(virgin$sepal.length,xlab = "virginica",ylab = "sepal.length")
plot(sepal.length, type = "h")
attach(virginica)
plot(petal.width, type = "h")
attach(specmap)
attach(virginica)
plot(sepal.length)
stripchart(speal.width)
attach(setosa)
stripchart(sepal.length, method = "stack")
attach(versicolor)
sl_density<-density(sepal.width)
plot(sl_density,ylab = "versicolor sepal.width density",main = "Density (x=sepal.width)", xlab = "Versicolor N=50 Bandwidth=0.1292")
qqnorm(sepal.length, ylab = "sepal.length values")
mytable<-table(virginica$sepal.length)
lbls<-paste(names(mytable),"\n",mytable,sep = "")
pie(mytable, labels = lbls,
    main="Pie Chart of Species\n (with sample sizes)")
install.packages("corrplot")
require(corrplot)
attach(virginica)
M<-cor(iris[,-c(5:10)])
corrplot(M)
corrplot(M,method = "ellipse")
attach(virginica)
virginica$sepal.length<-list(50)
samplelist<-virginica$sepal.length
samplelist<-list(50)
library(glyphs)
install.packages("glyphs")
